### ISSUE TITLE
Vai se limitar na facilidade de aprendizagem?

### ISSUE THREAD

**Issue by DenisPower1** [LUK3D-Angola/NOS#4]
A linguagem parece ser bem  interessante, apesar de não ter visto ela ainda em ação, mas por que se limitar apenas na facilidade de aprendizagem? 

A linguagem está sendo escrita em *Python*, *Python* também é bastante simples, e de uma certa forma facilita bastante para quem vai começar na área, mas ela não se limita à isso.

E deveria ter uma parte na documentação que faz a comparação entre a linguagem(Nos) e o *Portugol*, sendo que ambas têm o mesmo foco.

**Comment by LUK3D** [comment]
@DenisPower1 
Ela não irá se limitar apenas em facilitar o processo de aprendizagem. Tem vários benefícios e diferente de python, o nós não é muito exigente em termos de organização de código. Para iniciantes é muito difícil seguir a regra de tabulação do python e por outra, nem o python e nem o visualg ou portugol têm suporte a programação visual por diagramas de bloco. Além disso o Nós tem suporte a múltiplos idiomas também entre outras particularidades... pas não iremos parar só na educação.

**Comment by DenisPower1** [comment]
@LUK3D Fixe, ela foi escrita em Python e Javascript certo? Cadê os arquivos .js só vejo o .py.

**Comment by Nurul-GC** [comment]
@DenisPower1 está é uma questão que já está a ser resolvida, o projecto está em fase de testes e reorganização por isso ainda será difícil localizar os scripts *js*..

Mas na pasta 'nos-ide' poderás encontrar alguns..
